name: TruffleHog Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      - name: Install truffleHog
        run: |
          pip install truffleHog

      - name: Clone internal repository
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/pushpalathanelluri/samplerepo.git internal-repo

     
      - name: Run truffleHog scan on internal repo
        run: |
          trufflehog --entropy=True --json --regex https://github.com/pushpalathanelluri/samplerepo.git > trufflehog_internal_report.json



      - name: Upload public repo truffleHog report
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-public-report
          path: trufflehog_public_report.json

      - name: Upload internal repo truffleHog report
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-internal-report
          path: trufflehog_internal_report.json
