name: TruffleHog Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      - name: Install truffleHog
        run: |
          pip install truffleHog

      - name: Print truffleHog version
        run: |
          trufflehog --version

      - name: Print truffleHog help
        run: |
          trufflehog --help

      - name: Run truffleHog scan on public repo
        run: |
          trufflehog --entropy=True --json --regex https://github.com/pushpalathanelluri/samplerepo.git > trufflehog_public_report.json || { echo 'truffleHog failed'; exit 1; }

      - name: Upload public repo truffleHog report
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-public-report
          path: trufflehog_public_report.json
