name: TruffleHog Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      
      - name: Install truffleHog
        run: |
          pip install truffleHog

      - name: Print truffleHog version
        run: |
          trufflehog --version

      - name: Print truffleHog help
        run: |
          trufflehog --help
  scanning:
    name: TruffleHog Enterprise scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all history so multiple commits can be scanned
      - name: TruffleHog Enterprise scan
        uses: trufflesecurity/TruffleHog-Enterprise-Github-Action@main
        with:
            args: --fail-verified ${{ github.event.repository.default_branch }} HEAD
